language: python

python:
 - '3.7'

before_script:
 - pipenv install

env : DJANGO_SETTINGS_MODULE="brooze.settings.travis"

# branches:
#  only:
#   - staging

services:
 - postgresql

addons:
  postgresql: 12
  apt:
    packages:
    - postgresql-12-postgis-3
    - postgresql-12-postgis-3-scripts
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis"

script:
 - python manage.py test