language: python

python:
 - '3.8'

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo aptitude gdal-bin libgdal-dev python3-gdal binutils libproj-dev

env : DJANGO_SETTINGS_MODULE="brooze.settings.travis"

# branches:
#  only:
#   - staging

services:
 - postgresql

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
      
before_script:
  - psql -U postgres -c "create extension postgis"
  - pipenv install


script:
 - python manage.py test