language: python

python:
 - '3.8'

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update

env : DJANGO_SETTINGS_MODULE="brooze.settings.travis"

# branches:
#  only:
#   - staging

services:
 - postgresql

addons:
  apt:
    packages:
      - postgresql-11
      - postgresql-11-postgis-2.5
      - postgresql-11-postgis-2.5-scripts
  postgresql: '11'

before_script:
  - psql -U postgres -c "create extension postgis"
  - pipenv install


script:
 - python manage.py test