# Generated by Django 3.1.3 on 2020-12-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_auto_20200907_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
