# Generated by Django 3.0.5 on 2020-04-21 12:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('amenity', models.CharField(max_length=255, null=True)),
                ('addrhousenumber', models.CharField(max_length=255, null=True)),
                ('addrstreet', models.CharField(max_length=255, null=True)),
                ('addrcity', models.CharField(max_length=255, null=True)),
                ('addrpostcode', models.CharField(max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
