# Generated by Django 3.1.3 on 2020-12-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shops',
            options={'verbose_name_plural': 'shops'},
        ),
        migrations.AddField(
            model_name='shops',
            name='node_id',
            field=models.IntegerField(null=True),
        ),
    ]
